---
- hosts: localhost
  become: false
  tasks:

    - name: Pull latest calculator image
      community.docker.docker_image:
        name: meenal933/calculator
        source: pull

    - name: Run calculator container
      community.docker.docker_container:
        name: calculator
        image: meenal933/calculator
        state: started
        ports:
          - "8000:8000"
        recreate: true