---
- hosts: localhost
  become: false
  tasks:

    - name: Pull Docker Image
      command: docker pull meenal933/calculator

    - name: Stop existing container
      command: docker stop calculator
      ignore_errors: yes

    - name: Remove old container
      command: docker rm calculator
      ignore_errors: yes

    - name: Run Docker Container
      command: docker run -d -p 8000:8000 --name calculator meenal933/calculator